#pragma once

#include "AnimationSystem.h"
#include "CallbackSystem.h"
#include "CollectibleSystem.h"
#include "EnemySystem.h"
#include "FlagSystem.h"
#include "MapSystem.h"
#include "MenuSystem.h"
#include "PhysicsSystem.h"
#include "PlayerSystem.h"
#include "RenderSystem.h"
#include "ScoreSystem.h"
#include "SoundSystem.h"
#include "WarpSystem.h"
